### PR TITLE
fix journal form

### LINKED ISSUE #94: Policies Input fields border are overlapping
### **Describe the bug**
There are 4 input fields under Policies and there is no margin between them, so when focused on the given border(mainly the bottom border) is being hidden behind the other input field

### **Expected behaviour**
The Input field's border should not overlap.

### **Screenshots**

Code is Science - Google Chrome 4_4_2022 6_26_31 AM

### **To Reproduce**
Steps to reproduce the behaviour:
   1. Go to the Journals page
   2. 2. Check the Policies input field

### **Desktop:**
OS: Windows 11
Browser: Chrome
Version: 100.0.4896.60

### PR DESCRIPTION
**Pull request by roshanchatei**
## Description

Added bottom margin to the input fields so that when focused on the input field, the bottom border is not being hidden behind the other input field

Fixes #94 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.

### CODE REVIEW

**Review by padmajabhol — CHANGES_REQUESTED** [review]
Hi @roshanchatei , why do we need the ./idea folder? If not, please delete it. Apart from that, everything looks fine.

**Comment by roshanchatei** [comment]
@padmajabhol its because I use IntelliJ IDEA as my text editor, to remove it the maintainer needs to add '/.next/' to .gitignore

**Comment by padmajabhol** [comment]
> @padmajabhol its because I use IntelliJ IDEA as my text editor, to remove it the maintainer needs to add '/.next/' to .gitignore

You can do this when you send a commit or add additional commits in this particular PR to do the same.

**Comment by roshanchatei** [comment]
> > @padmajabhol its because I use IntelliJ IDEA as my text editor, to remove it the maintainer needs to add '/.next/' to .gitignore
> 
> You can do this when you send a commit or add additional commits in this particular PR to do the same.

Ok

**Comment by roshanchatei** [comment]
@padmajabhol now can you check it out

**Comment by ikayz** [comment]
@padmajabhol are you good with this now?

**Comment by padmajabhol** [comment]
> @padmajabhol are you good with this now?

Couldn't check, was away for a few days, doing right away.

**Review by padmajabhol — COMMENTED** [review]
I'm not sure but I'm not able to click on anything on your branch, can you look into this? Let me know if you need help. Sorry for the late review since I was away for a few days.

**Comment by roshanchatei** [comment]
> I'm not sure but I'm not able to click on anything on your branch, can you look into this? Let me know if you need help. Sorry for the late review since I was away for a few days.

Ok, I will look into it

**Pull request closed without merging**
