### PR TITLE
Manifesto - Remove title images and extra whitespace in portrait mode.

### LINKED ISSUE #109: Manifesto - Title images aligning vertically in smaller screens.
Thank you for taking the time to file a Bug report.

**Describe the bug**
On the manifesto page, there are two images on either side of the title, all aligned horizontally, but when the screen size is shrunk to be in a portrait mode, the title and the images are aligning vertically, also the padding is extraneous and is leaving lots of white space above and below the title.

**To Reproduce**

1. Go to the manifesto page
2. Reduce the screen size so that the window is in portrait orientation.
3. The images that were originally on either side of the title will now be aligned vertically.

**Expected behavior**
It is preferable not to show any images both above and below the title in portrait mode, as in smartphones, I feel it is important to deliver the content first. A media query can be written to hide these images below a certain breakpoint. Also removing the extra whitespace below and above the title in portrait mode can be written in the media query.
**Screenshots**
wrap

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome
- Version 100

**Additional context**
After a workaround, the final result would look something like this which I is believe is neat and concise.
wrap

### PR DESCRIPTION
**Pull request by prajwalkulkarni**
# Pull Request Template

## Description

Added media query for the title section of the manifesto page. Hides images around the title and removes extra whitespace around the title below screen width of 768px(standard breakpoint).

Fixes #109 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue).

## How Has This Been Tested?

Manual testing performed in throttled mode simulating most the following smartphones 

- iPhone 12 pro
- iPhone SE
- iPhone XR
- Pixel 5
- Samsung Galaxy S8+
- Samsung Galaxy A51
- Galaxy fold
- Manual Responsive screen mode

In all the above cases, the results perfectly matched the expected behavior.

## Additional Context (Please include any Screenshots/gifs if relevant)
wrap

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.

### CODE REVIEW

**Comment by prajwalkulkarni** [comment]
@padmajabhol Kindly review this PR that fixes #109. Thanks.

**Comment by padmajabhol** [comment]
I might have missed but a contributor had already raised a similar issue. Really sorry about this. Is it okay if I assign you a different issue related to javascript? Please let me know.

**Comment by prajwalkulkarni** [comment]
Sure, no problem @padmajabhol. I'd be willing to look into the issue related to JS. Could you please assign me to that?

**Comment by prajwalkulkarni** [comment]
Sure, no problem @padmajabhol. I'd be willing to look into the issue related to JS. Also if you don't mind, may I know which issue addresses this? I actually went through all the open and closed issues/PR, although there was a PR that addressed the manifesto page (https://github.com/codeisscience/journal-policy-tracker-frontend/pull/90), this issue was not fixed in that PR.

**Comment by padmajabhol** [comment]
Sure!

**Comment by padmajabhol** [comment]
Since another contributor is not responding, I'm reopening this PR.

**Comment by prajwalkulkarni** [comment]
Great. I kindly request you to review the commit and let me know if any changes are to be made. Thank you.

**Review by padmajabhol — APPROVED** [review]
LGTM. Thanks @prajwalkulkarni !

**Pull request merged**
