### PR TITLE
navbar fixed for home page

### PR DESCRIPTION
**Pull request by roshanchatei**
@ikayz now review it, I have done as you said.

### CODE REVIEW

**Comment by roshanchatei** [comment]
@ikayz 
And please delete the other branch i.e.  "navbar-fix"

**Comment by roshanchatei** [comment]
@ikayz ??

**Comment by roshanchatei** [comment]
@ikayz I just want to know if I have done it correctly or not so I can go forward. So if you are then please guide me.

**Comment by roshanchatei** [comment]
> @ikayz I just want to know if I have done it correctly or not so I can go forward. So if you are then please guide me.
*if you are free

**Comment by ikayz** [comment]
@roshanchatei I will look at it

**Comment by roshanchatei** [comment]
> @roshanchatei I will look at it
@ikayz thanks a lot
let me know as soon as possible.

**Comment by roshanchatei** [comment]
@ikayz have you checked it??

**Comment by ikayz** [comment]
@roshanchatei I had a look at the PR and it doesn't compile. Please see the attached screenshot
image

**Comment by roshanchatei** [comment]
@ikayz its working fine for me, I have attached the ss
Code is Science - Brave 2_9_2022 10_04_25 PM
Code is Science - Brave 2_9_2022 10_04_37 PM

**Comment by roshanchatei** [comment]
@ikayz ??

**Comment by ikayz** [comment]
@roshanchatei the first screenshot was on a Mac. I've attached a different screenshot on a Windows machine and getting the same error. 
image

**Comment by ikayz** [comment]
@roshanchatei the branch you made a PR from is roshan/navbar-fix correct?

**Review by ikayz — CHANGES_REQUESTED** [review]
@JPTIZ this PR has an error that's preventing the project from rendering. He needs to fix it first @roshanchatei. I've tried it on both Mac and Windows, the error is the same.

**Comment by ikayz** [comment]
@roshanchatei 
image

**Comment by roshanchatei** [comment]
> @roshanchatei the branch you made a PR from is roshan/navbar-fix correct?
@ikayz you are right.
I think I made a mistake while resolving conflict.
let me make a new PR.

**Comment by roshanchatei** [comment]
@ikayz I made a mistake while resolving the conflict
● Header css - journal-policy-tracker-frontend - Visual Studio Code 2_11_2022 9_59_25 PM
Just add '}' at line 7 of Header.css and It will work.
I am really sorry.

**Comment by roshanchatei** [comment]
@ikayz can u please add '}' in Header.css and check if it's working or not.
And let me know if its working or not so that I can make some more changes.

**Comment by roshanchatei** [comment]
I am not able to push again to the same branch so I asked you to add '}' 
Hyper 2_11_2022 10_12_18 PM

So what should I do: Make a new PR??

**Comment by roshanchatei** [comment]
@ikayz

**Comment by roshanchatei** [comment]
@JPTIZ @ikayz ?

**Comment by yochannah** [comment]
@roshanchatei Please do remember that this is a volunteer project, so responses may take a few days sometimes 😁

**Comment by JPTIZ** [comment]
> I am not able to push again to the same branch so I asked you to add '}' Hyper 2_11_2022 10_12_18 PM
> 
> So what should I do: Make a new PR??

Hm, did you overwrite any previous commit (for example, with `git commit --amend` or something like, or even a `git rebase [...]`) on you local history? If it is the case and you are 100% sure your local history is fine (for example, that you didn't delete a commit by accident and the changes are just as you expected them to be), try using `--force-with-lease` on `git push`.

**Comment by ikayz** [comment]
@roshanchatei try what @JPTIZ has suggested

**Comment by roshanchatei** [comment]
> @roshanchatei Please do remember that this is a volunteer project, so responses may take a few days sometimes 😁

ok, I will keep that in mind.

**Comment by roshanchatei** [comment]
> > I am not able to push again to the same branch so I asked you to add '}' Hyper 2_11_2022 10_12_18 PM
> > So what should I do: Make a new PR??
> 
> Hm, did you overwrite any previous commit (for example, with `git commit --amend` or something like, or even a `git rebase [...]`) on you local history? If it is the case and you are 100% sure your local history is fine (for example, that you didn't delete a commit by accident and the changes are just as you expected them to be), try using `--force-with-lease` on `git push`.

thanks for helping me out.
let me check and get back.

**Comment by roshanchatei** [comment]
@ikayz @JPTIZ
Now check it!

**Comment by roshanchatei** [comment]
@ikayz @JPTIZ ??

**Comment by JPTIZ** [comment]
> @ikayz @JPTIZ ??

Hey, don't worry, I have a queue of issues I have to check so you don't need to ping from time to time. Some of us get very busy so reviewing is not always so quick, I gently ask you to be patient :)

Unless, of course, you're in a hurry (needing to finish a contribution so you get evaluated in an interview or something like that).

**Comment by ikayz** [comment]
@roshanchatei thanks for the PR, there seems to be another issue. Please refer to the screenshot. I ran the project using the `roshan/navbar-fix` branch
Screenshot 2022-02-19 at 10 38 49

**Comment by roshanchatei** [comment]
> @roshanchatei thanks for the PR, there seems to be another issue. Please refer to the screenshot. I ran the project using the `roshan/navbar-fix` branch Screenshot 2022-02-19 at 10 38 49

I have used Material UI, so you need to install its dependencies before running.
npm install @mui/material @emotion/react @emotion/styled

**Comment by roshanchatei** [comment]
> > @ikayz @JPTIZ ??
> 
> Hey, don't worry, I have a queue of issues I have to check so you don't need to ping from time to time. Some of us get very busy so reviewing is not always so quick, I gently ask you to be patient :)
> 
> Unless, of course, you're in a hurry (needing to finish a contribution so you get evaluated in an interview or something like that).

I am really sorry about it, I won't do it again.
Actually, I am not in a hurry, I fixed the issue from the 'master' branch, but Issac asked me to work on the latest commit i.e. from the 'development' branch, so I did. I just want to know if I have done this correctly and if I am working on the latest commit of the development branch so I can start working on other pages navbar issue, that's all.

I am here to learn not for any interview evaluation, my friends recommended me to contribute to open source because it has one the best community and here I can learn new skills and improve my skills too as I learned from my GIT PUSH issue.

It would be very helpful if someone could tell me if I am working on the latest commit of the development branch, so I can start working on other pages navbar issues.

**Comment by ikayz** [comment]
@roshanchatei thanks for your efforts and work, however, I've noticed you are using new dependencies the project isn't using `Material UI and Emotion`. As of now, we are using React Bootstrap, I recommend you use that for your components. Having multiple UI libraries in the same project isn't a great idea at this stage and the Read me does mention React Bootstrap. Please do consult or refer to the contributing guide before adding dependencies the origin repo isn't using.

**Comment by roshanchatei** [comment]
> React Bootstrap

ok let me use react-bootstrap and then get back

**Comment by roshanchatei** [comment]
> @roshanchatei thanks for your efforts and work, however, I've noticed you are using new dependencies the project isn't using `Material UI and Emotion`. As of now, we are using React Bootstrap, I recommend you use that for your components. Having multiple UI libraries in the same project isn't a great idea at this stage and the Read me does mention React Bootstrap. Please do consult or refer to the contributing guide before adding dependencies the origin repo isn't using.

ok let me use react-bootstrap and then get back

**Comment by ikayz** [comment]
Awesome thanks 🙏🏾

**Comment by ikayz** [comment]
@roshanchatei just checking on this issue. If you were able to make the requested changes or should it be assigned to someone else?

**Comment by roshanchatei** [comment]
Yes I am working on it

**Comment by roshanchatei** [comment]
> @roshanchatei just checking on this issue. If you were able to make the requested changes or should it be assigned to someone else?

my semester exams were going on, now I will be contributing to this project

**Comment by roshanchatei** [comment]
@yochannah @ikayz I had send an email for the Project Proposal can u you please check it out?

**Comment by roshanchatei** [comment]
@ikayz @yochannah ?

**Comment by yochannah** [comment]
@roshanchatei thanks for still working on this - let's try and keep discussions in issues on-topic where we can though, thanks! :) (and you're in the slack now too which will help :) )

**Pull request closed without merging**
