### PR TITLE
Improved layout of Manifesto page

### LINKED ISSUE #74: Improving Manifesto page's layout
**Is your feature request related to a problem? Please describe.**
When I visited the manifesto's page, I saw that the layout of the page was not that good and that ruined the user experience.

**Describe the solution you'd like**
I have changed the layout of the page a little and I want to change the complete layout of the page to improve UX. I have attached a screenshot below with the new changes as an idea.  

Please assign this issue to me @yochannah , @JPTIZ .

**Screenshots**

Previous

Screenshot (23)

After some changes

Screenshot (24)

In this way, the layout can be changed to improve the user experience.

### PR DESCRIPTION
**Pull request by Tanish2000**
# Improved Layout of Manifesto Page

## Description

Layout change in the contribution section of the manifesto page.

Fixes #74 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## Screenshot
Screenshot (24)

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by Tanish2000** [comment]
Please review @yochannah @ikayz

**Comment by ikayz** [comment]
@Tanish2000 thanks for your contribution, which issue does this contribution address and/or fix?

**Comment by Tanish2000** [comment]
It fixes [Issue #77](https://github.com/codeisscience/journal-policy-tracker-frontend/issues/74)

**Comment by yochannah** [comment]
This looks good to me - the visuals are nice and the code is really tidy. Thanks @Tanish2000 !

**Pull request merged**
