### PR TITLE
Links are connected to respective images

### LINKED ISSUE #121: Directly going to the link on clicking icon in contact page.
**Is your feature request related to a problem? Please describe.**
On the contacts page, multiple icons are there, but the links just below it.

**Describe the solution you'd like**
I would like to link the hyperlinks directly to the picture, so when they are clicked on the person is directly directed or taken to mail section.

### PR DESCRIPTION
**Pull request by Riturajrs**
# Pull Request Template

## Description

In contact page link are now connected to the images

Fixes #121 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality).

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.

### CODE REVIEW

**Comment by padmajabhol** [comment]
Hi @Riturajseal2001 can you please resolve the conflicts before we move to review your PR? Thanks.

**Comment by Riturajrs** [comment]
@padmajabhol Conflict is resolved

**Review by padmajabhol — APPROVED** [review]
LGTM!

**Comment by yochannah** [comment]
ah, this is my fault -we have another conflict, it looks pretty quick to resolve though

**Comment by Riturajrs** [comment]
I have resolved the conflict. @yochannah please review it.

**Comment by padmajabhol** [comment]
@yochannah I guess this is good to go now!

**Pull request merged**
