### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by ikayz**
The footer has been coded based on the design. This PR also includes minor changes to the Readme.

### CODE REVIEW

**Comment by ikayz** [comment]
@yochannah

**Comment by ikayz** [comment]
@yochannah New commits have been added to his PR includes the journal page and some minor code refactoring

**Comment by yochannah** [comment]
This looks gorgeous and the code is really neat and tidy 😍 I also loved all the accessibility and linting in the console - looking forward to seeing the number of things raised in teh linter decreasing but I'm sure that will happen in time 😁

**Comment by ikayz** [comment]
Thanks, that will be worked on. More features and code refactoring will be done once the main parts are sorted out.

**Pull request merged**
