### PR TITLE
Removed extra in LogIn and SignUp page

### PR DESCRIPTION
**Pull request by KinetiCore-Labs**
## Description
* There is an extra space below the footer on the Login and SignUp page
  Screenshot from 2022-04-08 23-59-19

*  There is extra horizontal space on the login and Signup Space also.
  Screenshot from 2022-04-08 23-59-32

## Solution
* I increased margin-bottom on 'Login.css' from '50px' to '200px'. This removed extra space below 'footer' in both 'signup' and 'login' page
 Screenshot from 2022-04-08 23-44-49

* I added a code in 'index.css' to remove extra horizontal space on the 'login' and 'signup' pages.
 Screenshot from 2022-04-08 23-45-02

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own 

- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have signed the commit message to agree to the Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by KinetiCore-Labs** [comment]
@padmajabhol @yochannah can you please review this PR and verify my changes in the code.

**Comment by padmajabhol** [comment]
A past PR was working on fixing this particular issue #71 . Let's wait a day for him to respond?

**Comment by KinetiCore-Labs** [comment]
Sure @padmajabhol , I will wait for your review

**Comment by KinetiCore-Labs** [comment]
@padmajabhol I just checked the website, the issue remains, and there isn't any new PR for this issue. Can you now please review my PR?

**Comment by padmajabhol** [comment]
Hi @anwersayeed , I tried running your code and I still found some white space below the footer? Can you check once? Let me know if you need help fixing this.

**Comment by KinetiCore-Labs** [comment]
@padmajabhol I have increased the margin, can you run it again and let me know if its working or not

**Comment by padmajabhol** [comment]
> @padmajabhol I have increased the margin, can you run it again and let me know if its working or not

I guess we have to refactor the code for the footer component, or wrap it inside a div and fix it to the bottom, could you try that?

**Comment by KinetiCore-Labs** [comment]
> > @padmajabhol I have increased the margin, can you run it again and let me know if its working or not
> 
> I guess we have to refactor the code for the footer component, or wrap it inside a div and fix it to the bottom, could you try that?

@padmajabhol I have fixed the page overflow and it's working fine this time, could you please check?

**Comment by KinetiCore-Labs** [comment]
@padmajabhol is this PR working fine??

**Comment by padmajabhol** [comment]
> @padmajabhol is this PR working fine??

Can you resolve the conflicts? I'll check asap.

**Comment by KinetiCore-Labs** [comment]
> > @padmajabhol is this PR working fine??
> 
> Can you resolve the conflicts? I'll check asap.

@padmajabhol I have resolved the conflicts, can you check?

**Comment by padmajabhol** [comment]
> > > @padmajabhol is this PR working fine??
> > 
> > 
> > Can you resolve the conflicts? I'll check asap.
> 
> @padmajabhol I have resolved the conflicts, can you check?

Sure

**Pull request merged**
