### PR TITLE
Made the navbar responsive

### PR DESCRIPTION
**Pull request by roshanchatei**
fixed issue #52 

Code is Science - Brave 1_31_2022 12_11_54 AM

### CODE REVIEW

**Comment by roshanchatei** [comment]
@yochannah please review it.

**Comment by roshanchatei** [comment]
@yochannah @ikayz please review it.

**Review by ikayz — CHANGES_REQUESTED** [review]
@roshanchatei thanks for your efforts and work on this issue. I would like to point out a few things in this PR. It's behind the development branch, please see https://journal-policy-tracker.netlify.app/ as it's running on the latest commit of the development branch. In your fix you seem to have gotten rid of the button on the landing page and the navigation bar isn't centred. Please, use the development branch to contribute. See screenshots for reference
navbar-fix image

development branch

**Comment by roshanchatei** [comment]
> 
@ikayz 
So, I should clone from the development branch and then work on it ??

**Comment by roshanchatei** [comment]
@ikayz thank you 
I will work on it.

**Comment by ikayz** [comment]
> > 
> @ikayz 
> So, I should clone from the development branch and then work on it ??

Yes

**Comment by ikayz** [comment]
> @ikayz thank you 
> I will work on it.

Awesome 👍

**Comment by yochannah** [comment]
closing this since this seems to be a duplicate of #58

**Pull request closed without merging**
