### PR TITLE
Basic form validation and success / error alerts added

### LINKED ISSUE #75: Inconsistent codebase
**Describe the bug**

Codebase is not consistent. Login.js is a React **class component** while all other components in the codebase are React **functional components**.

**Expected behavior**

Whole codebase should be **consistent**. Either use React functional component or React class component. Otherwise it will become difficult for the developer to manage the codebase in **future**.

**Screenshots**

login

### PR DESCRIPTION
**Pull request by NumanAnees**
Signed-off-by: Numan Anees [numananees44@gmail.com](mailto:numananees44@gmail.com)
Fixes #75  and #76 

## Description

- ## 1st Issue Fix
- I have solved the issue of **Inconsistent codebase** by converting the whole code of login.js from react class component to react functional component. 
 
- login2

- ## 2nd Issue Fix
- I have added some basic validation so that user cannot submit empty forms. In future when datatype is clear we can add complete validation like ```password should be more than 8 characters long etc``` in my **validate helper funtion**.
- valid

- ## Success and Error Alert feature added
- User experience **Improved** by using success and error alerts made with css instead of using javascript 's simple alert box. After successfuly adding the Journal the ```input fields will become empty``` for new data.
- ### Before
- a1
- ### After
- a3

## Video

https://user-images.githubusercontent.com/67089723/161396375-771cc4b1-f859-4024-93bd-d2fe42820cf4.mp4

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by NumanAnees** [comment]
Please review @yochannah @ikayz

**Comment by NumanAnees** [comment]
@padmajabhol can you please review this?

**Comment by padmajabhol** [comment]
@NumanAnees this issue is currently under review and might need two approvals, meanwhile you can work on other bugs.

**Comment by padmajabhol** [comment]
These changes look good to me but I'll like an additional review from @ikayz just to be sure.

**Comment by ikayz** [comment]
@padmajabhol looks good to me

**Pull request merged**
