### PR TITLE
Redo navbar component

### LINKED ISSUE #166: Remove react bootstrap for landing page, navbar and footer.
Class based components, css dependecies have to be removed from the above mentioned components.

### PR DESCRIPTION
**Pull request by padmajabhol**
# Pull Request Template

## Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #166

### CODE REVIEW

**Comment by padmajabhol** [comment]
@ikayz I have removed the searchbar since it does not really serve any purpose for now.

**Comment by d-e-v-esh** [comment]
Won't the contents of the navbar need to be vertically centered?
image

**Comment by padmajabhol** [comment]
> Won't the contents of the navbar need to be vertically centered? image

It's not centered because I removed the search-bar. 
It's just for now, I ll come up with a better design at the end of soc as we had planned.

**Comment by ikayz** [comment]
@padmajabhol oh, okay. So what's the plan for that part?

**Comment by padmajabhol** [comment]
> @padmajabhol oh, okay. So what's the plan for that part?

We probably need to introspect as per why do we need a search-bar here? What do we want the user to search for ? 
Search-bars are mostly common in documentation websites. Since this isn't one, everything that one may search for is already available on the navbar itself.

**Pull request merged**
