### PR TITLE
sticky navbar

### LINKED ISSUE #88: Navbar should be sticky for better user experience
## According to the Google
nav_sticky

## Current Behaviour

https://user-images.githubusercontent.com/67089723/161424191-bacd67af-30d4-4464-8a3b-b71247e8e2b2.mp4

## Expected Behaviour

https://user-images.githubusercontent.com/67089723/161425139-b3dd2b1d-fba5-4818-b953-55174689178f.mp4

# Navigation Issue
There is a small navigation issue in the navbar. On clicking the ```code is science``` logo your website should navigate users to Home page. I've not opened a new issue for this because issue is very small. Should I open a new issue?

## Current behaviour
https://user-images.githubusercontent.com/67089723/161425040-a94bf05c-6115-46a7-bb76-97c68bf75ad6.mp4

## Expected Behaviour

https://user-images.githubusercontent.com/67089723/161425210-814f6d61-ecb9-4fbb-a2bc-b1d37ea775e6.mp4

### PR DESCRIPTION
**Pull request by NumanAnees**
## Description

I've fixed the issue of sticky navbar.

Fixes #88 

## Type of change

- [x] New feature (non-breaking change which adds functionality).

## Additional Context (Please include any Screenshots/gifs if relevant)

https://user-images.githubusercontent.com/67089723/161450615-c5ef08ed-e608-4bb3-8a99-ac86c0f928bd.mp4

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by NumanAnees** [comment]
@padmajabhol Please review it.

**Review by padmajabhol — CHANGES_REQUESTED** [review]
Right now, we are using react-bootstrap, just add `fixed="top"` to the Navbar and it should do the job. Adjust the padding in the navbar component itself. I don't think we need to change CSS across all the pages that are importing the navbar.

**Comment by vedeepika** [comment]
Can I work on this issue?

**Comment by padmajabhol** [comment]
Hi @vedeepika , this issue has already been taken and being worked upon. I'll review the issues that you have created and see if we need them.

**Comment by NumanAnees** [comment]
@padmajabhol I don't think adjusting the padding in navbar component will solve the problem. Content which is under the navbar require top padding. Other solution of this padding problem is to just give ```padding-top : 6em``` in body. It is a 1 line solution but I don't think it is good practice.

**Review by padmajabhol — APPROVED** [review]

**Pull request merged**
