### PR TITLE
Move content to config and images to cloudinary

### LINKED ISSUE #164: Move website content to config folder, use cloudinary for storing assets

### PR DESCRIPTION
**Pull request by padmajabhol**
# Pull Request Template

## Description
This PR moves all the content to the config/ folder and stores them in the form of js objects. We are moving all images to Cloudinary for better optimization and performance.

Fixes #164

### CODE REVIEW

**Comment by ikayz** [comment]
@padmajabhol this is a WIP, so I can merge the current PR?

**Comment by padmajabhol** [comment]
> @padmajabhol this is a WIP, so I can merge the current PR?

I'll get this PR done by EOD. There are some pages that I haven't moved.

**Comment by ikayz** [comment]
@padmajabhol reviewed, I've seen there is the config directory now. Are the assets in the `assets` directory going to be moved or you have a different plan for those?

**Review by ikayz — COMMENTED** [review]
Good to go, reviewed and checked. Just a minor change to the footer year, it's been hard coded.

**Comment by padmajabhol** [comment]
> @padmajabhol reviewed, I've seen there is the config directory now. Are the assets in the `assets` directory going to be moved or you have a different plan for those?

They don't have to stay there, I will delete them as we go changing the code in each page.

**Comment by padmajabhol** [comment]
> Good to go, reviewed and checked. Just a minor change to the footer year, it's been hard coded.

My bad, I didn't notice, will change that.

**Pull request merged**
