### PR TITLE
Fixed header background image response to change in screen size

### LINKED ISSUE #69: Background image gets cropped out when screen size is varied
Thank you for taking the time to file a Bug report.

**Describe the bug**
Background image in the header is not responsive. Also the header button overflows the header section.

**To Reproduce**

1. Go to [journal_policy_tracker_app](https://journal-policy-tracker.netlify.app/)
2. Right-click the mouse button and then click on 'inspect '
3. Set the dimentions to 'Responisve'  and decrease the window size to 800px.

**Expected behavior**
The background image in the header should not get cropped when changing the screen size and the button should be inside of the header section.

**Screenshots**
Error

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser Chrome
- Version 99

### PR DESCRIPTION
**Pull request by predator4hack**
## Description

The background image in the header section of homepage wasn't reponsive and gets cropped out when screen size is varied.

Fixes #69 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (Button element is responsive).
- [x] New feature (background image in the header section is responsive).

## Additional Context (Please include any Screenshots/gifs if relevant)

demo
...

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.

### CODE REVIEW

**Comment by ORKO06** [comment]
@predator4hack I have already sent a pr for this issue. Hope you can close this.

**Comment by predator4hack** [comment]
Hi @ORKO06, I saw your PR fixing the button but if it doesn't fix the cropping of background image. I tried to fix that problem specifically through this PR. Also, I was facing troubles in fixing the background because of the behaviour of button. So I fixed that as well. Hope you'd understand.

**Comment by predator4hack** [comment]
JJ

**Comment by padmajabhol** [comment]
I guess we can only review this after #67 is merged.

**Pull request closed without merging**
