### PR TITLE
Add contact form validation

### LINKED ISSUE #123: Add form validation to contact form
Currently we don't have any kind of validation for the form present in the contact page.

### PR DESCRIPTION
**Pull request by prajwalkulkarni**
# Pull Request Template

## Description

I've made use of state hooks and conditional checks to validate the contact form. This system takes into account the validation in real-time, meaning the user need not click on submit explicitly to find out if the form is valid or not. Also, since the contact page component doesn't render any children components, there'd be no re-renders of children components unnecessarily(even if it did, we could make use of React.memo to prevent unnecessary re-renders). Additionally, I've also added this feature where the submit button is enabled only if all the inputs are valid, this would make sure that the user enters valid inputs in all the fields. Kindly refer to the attached video to get a clearer insight.

Fixes #123 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).

## How Has This Been Tested?

Manual testing has been performed in various browsers to make sure the behavior is consistent across.

## Additional Context (Please include any Screenshots/gifs if relevant)

https://user-images.githubusercontent.com/22348265/162789461-1ffd0d25-6a7f-4e84-a70b-10e240888eef.mp4

...

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.

### CODE REVIEW

**Comment by prajwalkulkarni** [comment]
@padmajabhol @yochannah @ikayz, Kindly review this PR and let me know if there are any more changes to be made. Thank you.

**Comment by ikayz** [comment]
@prajwalkulkarni sure thing. Will review, thanks for contribution.

**Review by padmajabhol — CHANGES_REQUESTED** [review]
Is it possible to integrate instant validation? Let's say a user gets the warnings just after leaving the input field instead of after clicking the send button. Also, we can include a warning in case a submits something else other than a correct mail format.

**Comment by prajwalkulkarni** [comment]
@padmajabhol , The current implementation uses instant validation only. In the video, I'm just showing that the submit button will not be enabled until all the inputs are valid. There is no need to click on the submit button to get an error message. You can verify the same in the code, where I've hooked validation functions to the `onChange` prop of every input field, meaning validation is checked on every keystroke. Regarding the email format, when we use input type to be `email` the HTML itself takes care of the correct formatting, hence I didn't write an explicit function to validate the same.  But overall, the current implementation uses instant validation only. Kindly verify the same and let me know if there are any changes or updates to be made.

**Comment by padmajabhol** [comment]
> @padmajabhol , The current implementation uses instant validation only. In the video, I'm just showing that the submit button will not be enabled until all the inputs are valid. There is no need to click on the submit button to get an error message. You can verify the same in the code, where I've hooked validation functions to the `onChange` prop of every input field, meaning validation is checked on every keystroke. Regarding the email format, when we use input type to be `email` the HTML itself takes care of the correct formatting, hence I didn't write an explicit function to validate the same. But overall, the current implementation uses instant validation only. Kindly verify the same and let me know if there are any changes or updates to be made.

From instant validation, I meant their could be a warning right after the user leaves the input field. Maybe you could check this out https://stackoverflow.com/questions/38791919/call-a-function-after-leaving-input-field
Otherwise I think this is good to go and we can modify it later too.

**Review by padmajabhol — APPROVED** [review]

**Comment by prajwalkulkarni** [comment]
I believe that has been added too. I've hooked the functions to check for validation right after the user leaves the input field. This is accomplished by using the `onBlur` prop, I verified the same by looking through the answers posted in the Stackoverflow link that you've shared. The behavior is also reflected on the UI front. :)

**Pull request merged**
