### PR TITLE
Redesigned the contact component

### LINKED ISSUE #129: Redesigning the contact page
Thank you for taking the time to file a Bug report.

**Describe the bug**
There are two bugs in the contact page:

1. the color of the contact card looks bulky.
2. the contact form should be in the center.

**To Reproduce**

1. Go to the website (https://journal-policy-tracker.netlify.app/)
2. Click on the Contact link in the navbar
3. Scroll down to the contact form
4. See an error

**Actual behavior**

**Screenshots**
Screenshot (1030)

**Expected behavior**
The color of the contact card should be off-white, have a slightly greyish box-shadow, and have a hover transition. The contact form should be in the middle and add a heading 'send us a message above the contact form to enhance the user's experience.
**Screenshots**
ezgif com-gif-maker (8)

Screenshot (1043)

Desktop (please complete the following information):

OS: Windows 10
Browser: Chrome
Smartphone (please complete the following information):

Device: OnePlus Nord CE
OS: Android 11
Browser: Chrome

### PR DESCRIPTION
**Pull request by dikshashukla455**
# Pull Request Template

## Description

I have changed the styles of the contact card (the color of the card, added the box-shadow, and added the hover effect on the card.).I have added some headings in the contact form for enhancing the user's understandability and changed some styles in the form.

Fixes #129 

## Type of change

Please delete options that are not relevant.

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## How Has This Been Tested?

1. Go to the website
2. Click on the contact link which is present in the navbar
3. See the expected output

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code
- [x] I have signed the commit message to agree to the Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by padmajabhol** [comment]
I'm not sure but I'm not able to click on anything on your branch, can you look into this, at the same time resolve the conflicts on your branch. Sorry for the late review since I was away for a few days.

**Comment by dikshashukla455** [comment]
Sure, I will look at it.

**Comment by padmajabhol** [comment]
Sorry, the comment was meant for another PR, you can just resolve the conflicts and let me know.

**Comment by dikshashukla455** [comment]
> Sorry, the comment was meant for another PR, you can just resolve the conflicts and let me know.

Sure, just solving the conflicts.

**Pull request closed without merging**
