### PR TITLE
Creation of a responsive 'Read and Sign the Manifesto' button

### PR DESCRIPTION
**Pull request by neelimagoogly**
Updating Header.js and index.js to add functionality to the Header component.

Pull Request Template
Description
In in homepage of 'Code is Science' website , if we click on the 'Read and Sign the Manifesto' , it doesnot respond.
I have fixed this issue.

Fixes # (issue)
I have included the following changes to solve the issue:

- React Router Navigation
- Now when we click on the 'Read and Sign the Manifesto' button , it responds and redirects the user to the page where the user can read and sign the manifesto.

[ Yes] New feature (non-breaking change which adds functionality).

[ Yes] This change requires a documentation update.

How Has This Been Tested?
This has been tested in my local server 'localhost:3000'.

Checklist:
[ Yes] My code follows the style guidelines of this project.
[Yes ] I have performed a self-review of my own code.
[Yes ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by neelimagoogly** [comment]
Now I have successfully resolved this issue in a single PR #144 and and I have closed PR #138 .
Please review this .

**Comment by padmajabhol** [comment]
Please consider opening an issue prior to making a PR.

**Review by padmajabhol — APPROVED** [review]

**Comment by padmajabhol** [comment]
@ikayz I might need your approval here before we can set this to merge.

**Review by ikayz — COMMENTED** [review]
Good to go

**Pull request merged**
