### PR TITLE
Added techstack references and socialhandles

### PR DESCRIPTION
**Pull request by RitikaGarg-tech**
Pull Request

Description:

I have updated README.md by adding links for Javascript,CSS-(flexbox,grid),HTML-5,also provided numerous contact options for beginners like links to mailinglist,linkedin profiles for solving issues of beginners.

I am obliged to contribute to your project and love to connect to your community to learn and make contributions to the organization.

### CODE REVIEW

**Comment by padmajabhol** [comment]
Hi @RitikaGarg-tech , thankyou for contributing but please consider opening an issue to let us know what you want to work on. Sometimes, it might happen that we might not need it at all. And that could save a lot of efforts and time from the contributor's end.

**Comment by RitikaGarg-tech** [comment]
> Hi @RitikaGarg-tech , thankyou for contributing but please consider opening an issue to let us know what you want to work on. Sometimes, it might happen that we might not need it at all. And that could save a lot of efforts and time from the contributor's end.

Mam yes I will definately follow your valuable suggestions,if possible could you merge my pull request this time .

**Comment by padmajabhol** [comment]
> > Hi @RitikaGarg-tech , thankyou for contributing but please consider opening an issue to let us know what you want to work on. Sometimes, it might happen that we might not need it at all. And that could save a lot of efforts and time from the contributor's end.
> 
> Mam yes I will definately follow your valuable suggestions,if possible could you merge my pull request this time .

I'm not sure if we need this particular PR. Is it okay if I open a beginner friendly issue that you can work on?

**Comment by RitikaGarg-tech** [comment]
Mam if possible please guide me on how can I'm able to contribute to beginner-friendly issues.

**Pull request closed without merging**
