### PR TITLE
[UI] Added redirect property

### PR DESCRIPTION
**Pull request by afzal442**
Signed-off-by: afzal442 <afzal442@gmail.com>

Added redirect property to re-render the component

### CODE REVIEW

**Comment by afzal442** [comment]
Still not working;

Maybe we can work around it and this might help [us](https://answers.netlify.com/t/netlify-page-not-found-when-sharing-react-router-dom-based-links/11744/4).

**Comment by afzal442** [comment]
@yochannah @ikayz it works fine for me.

https://deploy-preview-28--journal-policy-tracker.netlify.app/contact

**Comment by ikayz** [comment]
@afzal442 I'll look at PR. I've seen the preview looks good. @yochannah you can also have a look

**Review by yochannah — APPROVED** [review]

**Comment by yochannah** [comment]
Looks good to me - @ikayz go ahead and merge when you've reviewed and you're ready

**Comment by ikayz** [comment]
@yochannah this has been merged. I've given it a try and seems to work fine. You give it a try

**Pull request merged**
