### PR TITLE
Routing fix for signup page

### LINKED ISSUE #37: User routing - Login
Routing users to Login after sign up

### PR DESCRIPTION
**Pull request by roshanchatei**
resolved #37

### CODE REVIEW

**Comment by yochannah** [comment]
@roshanchatei thanks for the PR! Are you able to take a look at the merge conflict before we review!

**Comment by roshanchatei** [comment]
> @roshanchatei thanks for the PR! Are you able to take a look at the merge conflict before we review!

I have resolved the conflict, now you can review

**Comment by roshanchatei** [comment]
@yochannah, I want to work on this project, there are many bugs, it's not responsive and I can also improve the UI.

I want to discuss the project with you or another mentor. If possible can you set a meeting in zoom or gmeet to discuss

Is there any other way to contact you or any other mentor like Email, Telegram, Twitter, etc?
 So can you please guide me?

**Comment by ikayz** [comment]
@roshanchatei this is issue is actually dependent on the backend. The routing should only happen with a successful sign up, failure to sign up shouldn't route but stay on the same page and just display an error.

**Comment by ikayz** [comment]
@roshanchatei also listing out the bugs you've found as issues would help us out a lot. Such as screenshots and descriptions in the issue for responsive bugs etc...

**Comment by roshanchatei** [comment]
> @roshanchatei this is issue is actually dependent on the backend. The routing should only happen with a successful sign up, failure to sign up shouldn't route but stay on the same page and just display an error.

If u want then u may merge the PR for now

**Comment by roshanchatei** [comment]
> @roshanchatei also listing out the bugs you've found as issues would help us out a lot. Such as screenshots and descriptions in the issue for responsive bugs etc...

sure I can do it

**Comment by roshanchatei** [comment]
@yochannah @ikayz is there any group to discuss it or we will be discussing it here only

**Comment by ikayz** [comment]
@roshanchatei For now here is fine, then will see how it goes

**Comment by roshanchatei** [comment]
> @roshanchatei For now here is fine, then will see how it goes

ok then, I have raised some issues.
I can directly start working on it, right??

Can I use libraries?

**Comment by roshanchatei** [comment]
https://summerofcode.withgoogle.com/archive/2021/projects/4885658513965056

I want to redesign this, make some improvements to the UI.
@yochannah @ikayz can u guide me?

**Comment by ikayz** [comment]
@roshanchatei have you read our documentation? Before you start working on anything?

**Comment by yochannah** [comment]
Hey @roshanchatei thanks so much for your offers to help! 

Right now the UI we have is around about 85% done and not quite yet at full release stage, so we're not really looking for any re-designs anytime soon! 

You've done a really nice job creating a few specific issues, but the titles and the descriptions could use a little updating - I'll go and add some notes on that!

**Comment by roshanchatei** [comment]
> @roshanchatei have you read our documentation? Before you start working on anything?

yes, I have read the documentation.

**Comment by roshanchatei** [comment]
> Hey @roshanchatei thanks so much for your offers to help!
> 
> Right now the UI we have is around about 85% done and not quite yet at full release stage, so we're not really looking for any re-designs anytime soon!
> 
> You've done a really nice job creating a few specific issues, but the titles and the descriptions could use a little updating - I'll go and add some notes on that!

That's very kind of you.
If you need a redesign in the UI anytime, I am ready to contribute and it will be my hour to help you all to complete the rest.

Updating the title and description of the issues would be a great help for me.

**Pull request merged**
